- .github/workflows/pr.yml
- gradle/wrapper/gradle-wrapper.properties
- Add gradle action and use for build.
- Update wrapper to gradle 7.4.2
> ci: Gradle updates

- core/src/main/java/io/substrait/expression/ExpressionCreator.java
- core/src/main/java/io/substrait/relation/ProtoRelConverter.java
- core/src/main/java/io/substrait/relation/RelChildVisitor.java
- core/src/main/java/io/substrait/relation/RelProtoConverter.java
- core/src/test/java/io/substrait/type/proto/AggregateRoundtripTest.java
- isthmus/src/test/java/io/substrait/isthmus/ProtoPlanConverterTest.java
- isthmus/src/test/java/io/substrait/isthmus/RelChildVisitorTest.java
Found and fixed bug causing aggregate function invocation to be dropped on roundtrip. Also added better test for aggregate function invocation.
> Fix bug causing aggregate function invocation to be dropped

- core/src/main/java/io/substrait/function/SimpleExtension.java
- core/src/main/java/io/substrait/relation/RelCopyOnWriteVisitor.java
- isthmus/src/test/java/io/substrait/isthmus/PlanTestBase.java
- isthmus/src/test/java/io/substrait/isthmus/ProtoPlanConverterTest.java
- isthmus/src/test/java/io/substrait/isthmus/RelCopyOnWriteVisitorTest.java
FYI, still need to add more tests.
> Copy on write visitor to allow simple plan modifications

- isthmus/README.md
Adds a basic README to Isthmus root — https://github.com/substrait-io/substrait-java/issues/44
> Adds Isthmus README.md

- isthmus/src/main/java/io/substrait/isthmus/SubstraitRelNodeConverter.java
- isthmus/src/test/java/io/substrait/isthmus/Substrait2SqlTest.java
> [ISTHMUS]support order by, limit offset clause in substrait to sql conversion

- isthmus/src/main/java/io/substrait/isthmus/expression/FunctionMappings.java
> register functions SUBSTRING, CONCAT in isthmus FunctionMappings

- core/src/main/java/io/substrait/function/SimpleExtension.java
- isthmus/src/test/java/io/substrait/isthmus/TpcdsQueryNoValidation.java
* Make intermediate field optional in function variant
* Add optional description field to function arg
* Add newly passing TPC-DS tests to test
> Upgrade substrait to 0.9.0

- .github/workflows/sanity.yml
- ci/release/sanity.sh
Utilities for sanity check for credentials configured on Github:
- In case we need to renew certificate or credentials for signing
- In case we need to renew credentials for Sonatype OSSRH
> ci: sanity check for credentials configured on Github

- .github/workflows/release.yml
- gradle/wrapper/gradle-wrapper.properties
> fix: release build failing #108

- .github/workflows/release.yml
To fix #108 #109
Testing at: https://github.com/daviddalisusanibararce/substrait-java/actions/runs/3546144738/jobs/5955051285
> fix: checkout submodules for release

- core/src/main/antlr/SubstraitType.g4
- core/src/main/java/io/substrait/expression/AggregateFunctionInvocation.java
- core/src/main/java/io/substrait/expression/Expression.java
- core/src/main/java/io/substrait/expression/FunctionArg.java
- core/src/main/java/io/substrait/expression/FunctionOption.java
- core/src/main/java/io/substrait/expression/WindowFunctionInvocation.java
- core/src/main/java/io/substrait/function/SimpleExtension.java
- core/src/main/java/io/substrait/relation/ProtoRelConverter.java
- core/src/main/java/io/substrait/relation/files/FileFormat.java
- core/src/main/java/io/substrait/relation/files/FileOrFiles.java
- core/src/main/java/io/substrait/type/parser/ParseToPojo.java
- core/src/test/java/io/substrait/type/parser/TestTypeParser.java
- core/src/test/java/io/substrait/type/proto/LocalFilesRoundtripTest.java
- isthmus/src/test/java/io/substrait/isthmus/CalciteCallTest.java
- isthmus/src/test/java/io/substrait/isthmus/RelCopyOnWriteVisitorTest.java
- Change Substrait.g4 to match [type-syntax spec](https://substrait.io/types/type_parsing/)
- Add optional field to function arg and bug fix for unit test
- Add newly passing test for ANY type
- Add Dwrf Read Options
> Upgrade substrait to 0.23.0

- core/src/main/java/io/substrait/function/SimpleExtension.java
- isthmus/src/main/java/io/substrait/isthmus/expression/FunctionMappings.java
- isthmus/src/test/java/io/substrait/isthmus/LogarithmicFunctionTest.java
PR to add logarithmic functions mapping and tests
> test: add mapping and test for logarithmic functions

- isthmus/src/main/java/io/substrait/isthmus/expression/FunctionMappings.java
PR to add comparison functions mapping
> feat: add comparison function mappings

- core/src/main/java/io/substrait/dsl/SubstraitBuilder.java
- core/src/main/java/io/substrait/relation/AbstractRelVisitor.java
- core/src/main/java/io/substrait/relation/ProtoRelConverter.java
- core/src/main/java/io/substrait/relation/RelCopyOnWriteVisitor.java
- core/src/main/java/io/substrait/relation/RelProtoConverter.java
- core/src/main/java/io/substrait/relation/RelVisitor.java
- core/src/main/java/io/substrait/relation/physical/MergeJoin.java
- core/src/test/java/io/substrait/type/proto/ExtensionRoundtripTest.java
- core/src/test/java/io/substrait/type/proto/JoinRoundtripTest.java
Closes https://github.com/substrait-io/substrait-java/issues/198
> feat: add MergeJoinRel

- core/src/main/java/io/substrait/relation/VirtualTableScan.java
- core/src/test/java/io/substrait/relation/VirtualTableScanTest.java
> fix: account for struct fields in VirtualTableScan check

- ci/release/publish.sh
Add spark to the CI publish script
> ci: publish spark module

- gradle.properties
- isthmus-cli/proxies.json
- isthmus/src/main/java/io/substrait/isthmus/SubstraitRelVisitor.java
- isthmus/src/main/java/io/substrait/isthmus/expression/ExpressionRexConverter.java
- isthmus/src/main/java/io/substrait/isthmus/expression/LiteralConverter.java
Update Calcite to 1.38.0: https://calcite.apache.org/docs/history.html#v1-38-0
> build: bump calcite from 1.37.0 to 1.38.0

- isthmus-cli/README.md
- isthmus-cli/src/main/java/io/substrait/isthmus/cli/IsthmusEntryPoint.java
- isthmus-cli/src/test/java/io/substrait/isthmus/cli/IsthmusEntryPointTest.java
- isthmus/src/main/java/io/substrait/isthmus/FeatureBoard.java
- isthmus/src/main/java/io/substrait/isthmus/SqlToSubstrait.java
- isthmus/src/test/java/io/substrait/isthmus/SimplePlansTest.java
BREAKING CHANGE: removed AllowsSqlBatch from FeatureBoard
> feat(isthmus): always allow batch queries

- spark/src/test/scala/io/substrait/spark/SubstraitPlanTestBase.scala
These functions are not used, so should be removed.
> chore: remove unused test utility code

- core/src/main/java/io/substrait/relation/AbstractRelVisitor.java
- core/src/main/java/io/substrait/relation/AbstractWriteRel.java
- core/src/main/java/io/substrait/relation/Extension.java
- core/src/main/java/io/substrait/relation/ExtensionWrite.java
- core/src/main/java/io/substrait/relation/NamedWrite.java
- core/src/main/java/io/substrait/relation/ProtoRelConverter.java
- core/src/main/java/io/substrait/relation/RelCopyOnWriteVisitor.java
- core/src/main/java/io/substrait/relation/RelProtoConverter.java
- core/src/main/java/io/substrait/relation/RelVisitor.java
- core/src/main/java/io/substrait/relation/extensions/EmptyDetail.java
- core/src/test/java/io/substrait/relation/utils/StringHolder.java
- core/src/test/java/io/substrait/relation/utils/StringHolderHandlingProtoRelConverter.java
- core/src/test/java/io/substrait/type/proto/WriteRelRoundtripTest.java
Add the Java bindings for the WriteRel proto message to the core package. Spark mappings to follow later.
> feat(core): add Write relation

- core/src/main/java/io/substrait/relation/AbstractRelVisitor.java
- core/src/main/java/io/substrait/relation/AbstractUpdate.java
- core/src/main/java/io/substrait/relation/NamedUpdate.java
- core/src/main/java/io/substrait/relation/ProtoRelConverter.java
- core/src/main/java/io/substrait/relation/RelCopyOnWriteVisitor.java
- core/src/main/java/io/substrait/relation/RelProtoConverter.java
- core/src/main/java/io/substrait/relation/RelVisitor.java
- core/src/test/java/io/substrait/type/proto/UpdateRelRoundtripTest.java
Add the POJOs for the UpdateRel proto message
> feat(core): add UpdateRel

- buildSrc/src/main/resources/substrait-pmd.xml
- core/src/main/java/io/substrait/expression/FieldReference.java
- core/src/main/java/io/substrait/type/parser/TypeStringParser.java
- examples/substrait-spark/src/main/java/io/substrait/examples/util/ParentStringify.java
- isthmus/src/main/java/io/substrait/isthmus/SubstraitRelVisitor.java
- isthmus/src/main/java/io/substrait/isthmus/Utils.java
- isthmus/src/test/java/io/substrait/isthmus/ApplyJoinPlanTest.java
- removes unused local variables
- removes unused assignments
- removes unused private fields
- removes unused private methods
- configures a PMD rule for each
> style: cleanup unused code
