build.gradle.kts

When cloning the repo and running `./gradlew clean jar` the build will currently fail, because it requires a manual step to init the git submodule via `git submodule update --init --recursive`.
This commit adds a Gradle task that does that and also includes that task when compiling the project.
This currently depends on https://github.com/substrait-io/substrait-java/pull/7 but will be rebased once it's merged

Build: Add gradle task to init substrait submodule when building project 

---

isthmus/src/main/java/io/substrait/isthmus/SqlToSubstrait.java

To prevent COUNT DISTINCT from turning into GROUP BY plus JOIN, remove the AggregateExpandDistinctAggregatesRule from being added to the Calcite program for the HepPlanner.

Remove AggregateExpandDistinctAggregatesRule

---

core/src/main/java/io/substrait/expression/FunctionLookup.java
core/src/main/java/io/substrait/expression/proto/ImmutableFunctionLookup.java
core/src/main/java/io/substrait/expression/proto/ProtoExpressionConverter.java
core/src/main/java/io/substrait/relation/Join.java
core/src/main/java/io/substrait/relation/ProtoRelConverter.java
core/src/main/java/io/substrait/relation/RelConverter.java
core/src/main/java/io/substrait/type/proto/FromProto.java
core/src/test/java/io/substrait/type/proto/GenericRoundtripTest.java
core/src/test/java/io/substrait/type/proto/LiteralRoundtripTest.java
isthmus/src/test/java/io/substrait/isthmus/ProtoRelConverterTest.java

Processing on Substrait plans in Java is much more clearly accomplished by working with the POJO representation rather than the serialized proto representation. The ProtoRelConverter class implements this with the help of the existing ProtoExpressionConverter class.

Converter for proto to pojo rel representation

---

isthmus/src/main/java/io/substrait/isthmus/SqlToSubstrait.java
isthmus/src/main/java/org/apache/calcite/jdbc/LookupCalciteSchema.java
isthmus/src/test/java/io/substrait/isthmus/TableLookupTest.java

This uses a function to look up a table schema without a create table statement. I've intentionally kept the interface free from calcite objects so as to not export them as part of the isthmus public API.
I am not an expert at calcite so I am not sure if this is the best way to do it. Also, note, my fix adds state to the converter. Happy to adjust based on input.

Add table lookup entry point to SqlToSubstrait

---

bom/build.gradle.kts
build.gradle.kts
core/build.gradle.kts
isthmus/build.gradle.kts

this allows for the java modules to be published to a local maven repository (eg `~/.m2/repository` for integration with other local projects.

Add publishToLocalMaven command

---

core/src/main/java/io/substrait/plan/Plan.java
core/src/main/java/io/substrait/plan/PlanProtoConverter.java
core/src/main/java/io/substrait/plan/ProtoPlanConverter.java

Fix bug in Plan proto conversion caused by storing extension uris and functions in Plan pojo and using when generating proto instead of regenerating.

Generate extension uris and functions from pojos instead of storing

---

isthmus/src/main/java/io/substrait/isthmus/PlanEntryPoint.java
isthmus/src/main/java/io/substrait/isthmus/SqlToSubstrait.java
isthmus/src/test/java/io/substrait/isthmus/PlanTestBase.java
isthmus/src/test/java/io/substrait/isthmus/SimplePlansTest.java
isthmus/src/test/java/io/substrait/isthmus/Substrait2SqlTest.java
isthmus/src/test/java/io/substrait/isthmus/TableLookupTest.java

As a byproduct of having a multi-statement option, trailing semicolons will be ignored.

[ISTHMUS] Add --multistatement option to allow multiple sql statements

---

.gitignore
isthmus/src/main/java/io/substrait/isthmus/expression/FunctionMappings.java
isthmus/src/test/java/io/substrait/isthmus/TpchQueryNoValidation.java

add aggregation function min/max support, so the tpc-h Q2,Q15 could run success. Delivers #36

[ISTHMUS] Add aggregation function MIN/MAX support

---

core/src/main/java/io/substrait/function/ToTypeString.java
isthmus/src/main/java/io/substrait/isthmus/expression/FunctionMappings.java

sub-issue:
The emitted function signatures don't follow the spec.
For example, decimal is used instead of dec, and any1 is used in place of just any.

Fix issue #18

---

isthmus/src/main/java/io/substrait/isthmus/SubstraitRelVisitor.java
isthmus/src/main/java/io/substrait/isthmus/expression/CallConverters.java
isthmus/src/main/java/io/substrait/isthmus/expression/LiteralConstructorConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/RexExpressionConverter.java
isthmus/src/test/java/io/substrait/isthmus/TpchQueryNoValidation.java

Invoke `RexUtil.expandSearch` to do the conversion.

Issue #62: For calcite SqlSearchOperator expand the Sarg Literals into a simple predicates.

---

build.gradle.kts
core/build.gradle.kts
core/src/main/java/io/substrait/expression/FieldReference.java
core/src/main/java/io/substrait/function/SimpleExtension.java
core/src/main/java/io/substrait/relation/RelCopyOnWriteVisitor.java
core/src/main/java/io/substrait/relation/RelProtoConverter.java

This patch does the same thing as https://github.com/substrait-io/substrait-java/pull/95, but using jabel

Downgrade core to java 8 via Jabel

---

isthmus/build.gradle.kts
isthmus/src/main/java/io/substrait/isthmus/FeatureBoard.java
isthmus/src/main/java/io/substrait/isthmus/PlanEntryPoint.java
isthmus/src/main/java/io/substrait/isthmus/SqlConverterBase.java
isthmus/src/main/java/io/substrait/isthmus/SqlToSubstrait.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelVisitor.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitToSql.java
isthmus/src/test/java/io/substrait/isthmus/PlanEntryPointTest.java
isthmus/src/test/java/io/substrait/isthmus/ProtoPlanConverterTest.java
isthmus/src/test/java/io/substrait/isthmus/SimplePlansTest.java

This change adds a FeatureBoard, a collection of configuration and flags to control the behavior of SQL to Substrait conversion and vice versa. The original intent was to add a config for Calcite's conformance mode. Expecting more such changes in future, this PR adds a generic FeatureBoard which should provide sufficient hints to user (leveraging command-line help messages) and easier configuration using properties file (see picocli PropertiesDefaultProvider).
FeatureBoard replaces Options and is inspired by Feature Toggle design pattern. All configs are available in one place, instead of Options which required config hunting in multiple files. Also some Options were not accessible from command line. 
This change is backward compatible.

refactor: Add FeatureBoard for configuring Isthmus

---

core/src/main/java/io/substrait/relation/AbstractRelVisitor.java
core/src/main/java/io/substrait/relation/LocalFiles.java
core/src/main/java/io/substrait/relation/ProtoRelConverter.java
core/src/main/java/io/substrait/relation/RelProtoConverter.java
core/src/main/java/io/substrait/relation/RelVisitor.java
core/src/main/java/io/substrait/relation/files/FileFormat.java
core/src/main/java/io/substrait/relation/files/FileOrFiles.java
core/src/test/java/io/substrait/type/proto/LocalFilesRoundtripTest.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelNodeConverter.java

Currently substrait-java doesn't implement `LocalFiles` ReadRel,  this patch adds this missing `Rel`.  
Add a new UT `LocalFilesRoundtripTest`

Add ReadRel LocalFiles

---

.github/workflows/pr.yml
ci/release/publish.sh
gradle/wrapper/gradle-wrapper.properties

To implement automatic promote from Staging to Maven Central on weekly releases.
Base on discussion on PR https://github.com/substrait-io/substrait-java/pull/104 (scenario 1 & 2).

fix: open, close and promote from staging to maven

---

isthmus/src/main/java/io/substrait/isthmus/OuterReferenceResolver.java
isthmus/src/main/java/io/substrait/isthmus/OuterReferenceResolver.md
isthmus/src/main/java/io/substrait/isthmus/SqlConverterBase.java
isthmus/src/main/java/io/substrait/isthmus/SqlToSubstrait.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelVisitor.java
isthmus/src/test/java/io/substrait/isthmus/ApplyJoinPlanTest.java

This change adds support for parsing of SQL queries with APPLY (join with
correlated subquery), and to build OuterReferences map of correlated variables
present in the query's join predicates. The OuterRefs will be used while
constructing Substrait plans to bind correlated variables. The change also
adds few example queries which depend on APPLY / LATERAL operators.
This change still does not map calcite-correlated-join to Substrait, as the
spec for APPLY is still not approved. As such, while the parsing of calcite
query plans will succeed after this change, the unit tests and run time
conversion will continue to fail in the final step of building the
Substrait plan. Additional changes are needed to support APPLY.
Refs #substrait-io/substrait/issues/357

feat: support parsing of SQL queries with APPLY

---

.github/workflows/pr.yml
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelNodeConverter.java

Adds a new constructor for `SubstraitRelNodeConverter` that allows for directly setting the `RelBuilder`. This allows users to directly configure the `RelBuilder` and to apply optimizations successfully to the plans generated by the converter.
The first commit in these changes introduces the new constructor. The following commits are all quality of life refactors (in my opinion). If they are not desirable I'm happy to remove them.
I'm trying to leverage the work in Isthmus to convert a Substrait relational tree to a Calcite relational tree, and then apply optimizations. I'm using the `SubstraitRelNodeConverter` to achieve the conversion, which works great, however there is an issue that occurs when trying to optimize the converted plan.
The problem stems from the following code in …

feat!: Set RelBuilder directly in SubstraitRelNodeConverter

---

.github/workflows/release.yml

To close #118
Upgrade node version for last changes on Semantic Release node version used:
semantic-release/semantic-release@ba05e08

ci: setup node v18 for semantic release process

---

core/src/test/java/io/substrait/type/proto/LocalFilesRoundtripTest.java
isthmus/src/main/java/io/substrait/isthmus/expression/FunctionMappings.java
isthmus/src/test/java/io/substrait/isthmus/Substrait2SqlTest.java

This PR added two string-related scalar functions in FunctionMappings.java to support generating query plans that involve `lower()` and `upper()` ops.
It included the following changes
- updated substrait version from 0.9.0 to 0.13.0 (which added string transform functions)
- added entries for `lower` and `upper` in FunctionMappings.java

feat: registered `upper` & `lower` in function mapping

---

isthmus/src/main/java/io/substrait/isthmus/FeatureBoard.java
isthmus/src/test/java/io/substrait/isthmus/PlanEntryPointTest.java

[SqlConformanceModeEnum](https://calcite.apache.org/javadocAggregate/org/apache/calcite/sql/validate/SqlConformanceEnum.html) extends SqlConformance, and has a fixed set of conformance modes. FeatureBoard accepting SqlConformance instead of SqlConformanceModeEnum enables more configurations. As an example, [FlinkSqlConformance](https://nightlies.apache.org/flink/flink-docs-master/api/java/org/apache/flink/sql/parser/validate/FlinkSqlConformance.html) can be passed in with this change.

refactor: Accept SqlConformance mode instead of SqlConformanceModeEnum in FeatureBoard

---

core/src/main/antlr/SubstraitType.g4
core/src/test/java/io/substrait/type/parser/TestTypeParser.java

The Decimal type is specified as `Decimal<P,S>` on https://substrait.io/types/type_classes/
The parser was configured to parse the first parameter as scale, and the second as precision.
```
Decimal isnull='?'? Lt scale=numericParameter Comma precision=numericParameter Gt #decimal
```
This PR fixes this and adds additional test coverage.

fix: decimal parsing reversed

---

core/src/main/java/io/substrait/dsl/SubstraitBuilder.java
core/src/main/java/io/substrait/relation/Join.java
isthmus/src/test/java/io/substrait/isthmus/SubstraitRelNodeConverterTest.java

During a left, right, or outer join, some set of fields from input become nullable because they are optionally matched in the output. For a left join, the right fields become nullable. For a right join, the left fields become nullable. For an outer join, both sets become nullable.
This test fails with assertions enabled in Calcite code because the left join should have nullable right types.

fix: Left/right/outer joins should have nullable fields.

---

core/src/main/java/io/substrait/dsl/SubstraitBuilder.java
core/src/main/java/io/substrait/expression/AggregateFunctionInvocation.java
core/src/main/java/io/substrait/expression/Expression.java
core/src/main/java/io/substrait/expression/ExpressionCreator.java
core/src/main/java/io/substrait/expression/WindowFunctionInvocation.java
core/src/main/java/io/substrait/relation/ProtoRelConverter.java
core/src/main/java/io/substrait/relation/RelProtoConverter.java
core/src/test/java/io/substrait/type/proto/AggregateRoundtripTest.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelNodeConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/AggregateFunctionConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/WindowFunctionConverter.java
isthmus/src/test/java/io/substrait/isthmus/RelCopyOnWriteVisitorTest.java

BREAKING CHANGE: various public functions that took the
AggregateFunction.AggregationInvocation proto now take the POJO
equivalent Expression.AggregationInvocation.

refactor(pojos)!: avoid using raw proto enums in POJO layer

---

core/src/main/java/io/substrait/expression/FieldReference.java
core/src/main/java/io/substrait/expression/proto/ExpressionProtoConverter.java
core/src/main/java/io/substrait/expression/proto/ProtoExpressionConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/RexExpressionConverter.java
isthmus/src/test/java/io/substrait/isthmus/NestedStructQueryTest.java

This test case will hit:
https://github.com/substrait-io/substrait-java/blob/4749dcad7eec5325414b0b08d7c2f0fdfc058378/isthmus/src/main/java/io/substrait/isthmus/expression/RexExpressionConverter.java#L128-L129
since `fieldAccess.getReferenceExpr()` is a `RexFieldAccess`

bug: fix vist of nested struct

---

core/src/main/java/io/substrait/expression/Expression.java
core/src/main/java/io/substrait/expression/ExpressionCreator.java
core/src/main/java/io/substrait/expression/proto/ExpressionProtoConverter.java
core/src/main/java/io/substrait/expression/proto/ProtoExpressionConverter.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitTypeSystem.java
isthmus/src/main/java/io/substrait/isthmus/TypeConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/ExpressionRexConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/LiteralConverter.java
isthmus/src/test/java/io/substrait/isthmus/CalciteLiteralTest.java
isthmus/src/test/java/io/substrait/isthmus/CalciteTypeTest.java

This PR :
- adds fractional second intervals to substrait-java
- fixes isthmus for INTERVAL_DAY conversion and add other day-time intervals
- adds literal conversion tests to isthmus
Fractional seconds where added to the Substrait specifications [in this PR from May 2022](https://github.com/substrait-io/substrait/pull/199).

feat: implement fractional second intervals, with tests

---

core/src/main/java/io/substrait/expression/Expression.java
core/src/main/java/io/substrait/expression/ExpressionCreator.java
core/src/main/java/io/substrait/expression/WindowBound.java
core/src/main/java/io/substrait/expression/proto/ExpressionProtoConverter.java
core/src/main/java/io/substrait/expression/proto/ProtoExpressionConverter.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelNodeConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/ExpressionRexConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/RexExpressionConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/WindowFunctionConverter.java
isthmus/src/test/java/io/substrait/isthmus/CustomFunctionTest.java
isthmus/src/test/java/io/substrait/isthmus/PlanTestBase.java
isthmus/src/test/java/io/substrait/isthmus/WindowFunctionTest.java

feat: support for window bounds type
BREAKING CHANGE:
* windowFunction expression creator now requires window bound type param
* the WindowBound POJO representation has been reworked to use visitation and more closely match the spec
* ExpressionRexConvert now requires a WindowFunctionConverter

feat: window function calcite support

---

isthmus/src/main/java/io/substrait/isthmus/SubstraitRelNodeConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/ExpressionRexConverter.java
isthmus/src/test/java/io/substrait/isthmus/ExpressionConvertabilityTest.java

feat: inject ExpressionRexConverter into SubstraitRelNodeConverter

feat(calcite): support reading in list and map literals

---

core/src/main/java/io/substrait/extension/SimpleExtension.java

allows for equality comparisons of Argument subclasses
BREAKING CHANGE: EnumArgument, TypeArgument and ValueArgument are now abstract

feat: use Immutables for Argument subclasses

---

core/src/main/java/io/substrait/dsl/SubstraitBuilder.java
core/src/main/java/io/substrait/expression/Expression.java
core/src/main/java/io/substrait/relation/Join.java
core/src/main/java/io/substrait/type/Type.java
core/src/main/java/io/substrait/type/TypeCreator.java
isthmus/src/main/java/io/substrait/isthmus/AggregateFunctions.java
isthmus/src/main/java/io/substrait/isthmus/SqlConverterBase.java
isthmus/src/main/java/io/substrait/isthmus/calcite/SubstraitOperatorTable.java
isthmus/src/main/java/io/substrait/isthmus/expression/FunctionMappings.java
isthmus/src/test/java/io/substrait/isthmus/AggregationFunctionsTest.java
isthmus/src/test/java/io/substrait/isthmus/ArithmeticFunctionTest.java
isthmus/src/test/java/io/substrait/isthmus/CalciteCallTest.java
isthmus/src/test/java/io/substrait/isthmus/CalciteLiteralTest.java
isthmus/src/test/java/io/substrait/isthmus/CalciteTypeTest.java
isthmus/src/test/java/io/substrait/isthmus/PlanTestBase.java

fix(calcite): address type inference mismatch in arithmetic aggregate functions
feat: util methods on TypeCreator for setting type nullability
feat: builder utils for arithmetic aggregate functions
feat(calcite): support sum0 sql function
test: static fields in Type interface caused NPEs in tests 
BREAKING CHANGE: Isthmus no longer uses Calcite built-in MAX, MIN, SUM, SUM0 and AVG functions
BREAKING CHANGE: removed REQUIRED and NULLABLE fields from Type interface

feat(calcite): dedicated Substrait MAX, MIN, SUM, SUM0 and AVG functions

---

core/build.gradle.kts

To avoid introducing unnecessary indirect dependencies. Resolve issue #162

build: use antlr4-runtime instead of antlr

---

core/src/main/antlr/SubstraitType.g4
core/src/main/java/io/substrait/function/ParameterizedType.java
core/src/main/java/io/substrait/function/ParameterizedTypeCreator.java
core/src/main/java/io/substrait/type/parser/ParseToPojo.java
core/src/test/java/io/substrait/extension/TypeExtensionTest.java
core/src/test/java/io/substrait/type/parser/TestTypeParser.java
core/src/test/resources/extensions/custom_extensions.yaml

This PR aims to make TypeParam support optional nullable suffix. To fix #169.
Added unit test TypeExtensionTest#arrayIndexScalarFunction

fix: `TypeParam` supports optional nullable suffix

---

core/src/main/java/io/substrait/dsl/SubstraitBuilder.java
core/src/main/java/io/substrait/expression/Expression.java
core/src/main/java/io/substrait/expression/ExpressionCreator.java
core/src/main/java/io/substrait/expression/proto/ExpressionProtoConverter.java
core/src/main/java/io/substrait/expression/proto/ProtoExpressionConverter.java
core/src/main/java/io/substrait/relation/RelCopyOnWriteVisitor.java
isthmus/src/main/java/io/substrait/isthmus/expression/ExpressionRexConverter.java
isthmus/src/test/java/io/substrait/isthmus/ExpressionConvertabilityTest.java
isthmus/src/test/java/io/substrait/isthmus/SubstraitExpressionConverterTest.java
isthmus/src/test/java/io/substrait/isthmus/SubstraitRelNodeConverterTest.java

The switch expression POJO in substrait-java doesn't contain the match expression, so I've updated the definition to include that.
To map into Calcite, I construct a CASE statement. This ends up being translated into an IfThen expression when round-tripping Substrait into Calcite.

fix: map switch expression to a Calcite CASE statement

---

core/src/main/java/io/substrait/dsl/SubstraitBuilder.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelNodeConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/ExpressionRexConverter.java
isthmus/src/test/java/io/substrait/isthmus/ExpressionConvertabilityTest.java

Added support for `Expression.InPredicate` into `ExpressionRexConverter`

feat(isthmus): support in-predicate (#204)

---

isthmus/src/main/java/io/substrait/isthmus/expression/FunctionMappings.java
isthmus/src/test/java/io/substrait/isthmus/StringFunctionTest.java

This PR adds a string-related scalar function mapping in `FunctionMappings` to support generating plans for queries that use the [`char_length`](https://www.postgresql.org/docs/current/functions-string.html#id-1.5.8.10.5.2.2.6.1.1.1) function.
It also introduces very basic unit tests for string-related functions, including the newly supported `char_length` one.

Added support for char_length

---

core/src/main/java/io/substrait/dsl/SubstraitBuilder.java
core/src/main/java/io/substrait/extension/DefaultExtensionCatalog.java
core/src/main/java/io/substrait/type/YamlRead.java
core/src/test/java/io/substrait/extendedexpression/ExtendedExpressionRoundTripTest.java
isthmus/src/main/java/io/substrait/isthmus/expression/EnumConverter.java

contains static strings for default extensions

feat: introduce DefaultExtensionCatalog

---

core/src/main/java/io/substrait/dsl/SubstraitBuilder.java
core/src/main/java/io/substrait/function/ToTypeString.java
isthmus/src/main/java/io/substrait/isthmus/AggregateValidator.java
isthmus/src/main/java/io/substrait/isthmus/PreCalciteAggregateValidator.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelNodeConverter.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelVisitor.java
isthmus/src/test/java/io/substrait/isthmus/AggregationFunctionsTest.java
isthmus/src/test/java/io/substrait/isthmus/ComplexAggregateTest.java
isthmus/src/test/java/io/substrait/isthmus/CustomFunctionTest.java
isthmus/src/test/java/io/substrait/isthmus/PlanTestBase.java
isthmus/src/test/java/io/substrait/isthmus/SubstraitRelNodeConverterTest.java

Substrait Aggregates that contain expressions that are not field
references and/or grouping keys that are not in input order require
extra processing to be converted to Calcite Aggregates successfully AND
correctly

feat(isthmus): improved Calcite support for Substrait Aggregate rels 

---

.github/workflows/pr.yml
.github/workflows/release.yml

To closes: https://github.com/substrait-io/substrait-java/issues/219

fix: semantic release requires Node version 20.8.1 or higher

---

core/src/main/java/io/substrait/type/parser/ParseToPojo.java
core/src/main/java/io/substrait/type/proto/ProtoTypeConverter.java
isthmus/src/main/java/io/substrait/isthmus/TypeConverter.java

Some clarification was added to the non-informative exceptions.

fix: some exceptions are not very informative for the client code (#221)

---

isthmus/src/main/java/io/substrait/isthmus/expression/FunctionMappings.java
isthmus/src/test/java/io/substrait/isthmus/StringFunctionTest.java

Function is available in [Calcite](https://github.com/apache/calcite/blob/4f5a08f5429ff905a2ebd96600b0966ba9e228ea/core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java#L1581-L1583) and [Substrait's functions_string.yaml](https://github.com/substrait-io/substrait/blob/3ded94d69e7ae329f2730b7634ba34900250e84a/extensions/functions_string.yaml#L771-L790), so just registering the mapping here.

feat(isthmus): support for replace

---

ci/release/README.md

Minor doc fix: I was reading up about the release process and noticed the artifacts link was resolving to 404.

fix: update bad URLs in the release readme

---

core/src/main/java/io/substrait/expression/AbstractExpressionVisitor.java
core/src/main/java/io/substrait/expression/Expression.java
core/src/main/java/io/substrait/expression/ExpressionCreator.java
core/src/main/java/io/substrait/expression/ExpressionVisitor.java
core/src/main/java/io/substrait/expression/proto/ExpressionProtoConverter.java
core/src/main/java/io/substrait/expression/proto/ProtoExpressionConverter.java
core/src/main/java/io/substrait/relation/ExpressionCopyOnWriteVisitor.java
core/src/main/java/io/substrait/type/TypeCreator.java
core/src/main/java/io/substrait/type/proto/ProtoTypeConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/CallConverters.java
isthmus/src/main/java/io/substrait/isthmus/expression/ExpressionRexConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/LiteralConstructorConverter.java
isthmus/src/test/java/io/substrait/isthmus/EmptyArrayLiteralTest.java

The substrait proto definition provides a representation of empty list literals which is separate from the
representation of non-empty list literals:
```
message Literal {
oneof literal_type {
...
List list = 30;
Type.List empty_list = 31;
...
}
}
```
This change gives substrait-java a representation for empty list literals, along with conversions to/from
protobuf and to/from Calcite in Isthmus.
BREAKING CHANGE:
* ExpressionVisitor has a new method to visit Expression.EmptyListLiteral. Implementors which don’t extend AbstractExpressionVisitor will have to add their own implementation.
* Public class LiteralConstructorConverter now requires a TypeConverter to be passed to its constructor.
* ExpressionCopyOnWriteVisitor#visitLiteral() may now be called with Expression.EmptyListLiteral.

feat: add support for empty list literals

---

core/src/main/java/io/substrait/expression/Expression.java
core/src/main/java/io/substrait/expression/ExpressionCreator.java
core/src/main/java/io/substrait/expression/ExpressionVisitor.java
core/src/main/java/io/substrait/expression/proto/ExpressionProtoConverter.java
core/src/main/java/io/substrait/expression/proto/ProtoExpressionConverter.java
core/src/main/java/io/substrait/relation/ExpressionCopyOnWriteVisitor.java
isthmus/src/main/java/io/substrait/isthmus/expression/CallConverters.java
isthmus/src/main/java/io/substrait/isthmus/expression/ExpressionRexConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/LiteralConverter.java
isthmus/src/test/java/io/substrait/isthmus/CustomFunctionTest.java

calcite does not accept RelDatatypes with sqltypename.OTHER and has no way of representing it as of now.
It will reject it at different steps such as [RexLiteral Precondition type check](https://github.com/apache/calcite/blob/c774c313a81d01c4e3e77cf296d04839c5ab04c0/core/src/main/java/org/apache/calcite/rex/RexLiteral.java#L231) or when building using the RexBuilder.
There's a [ticket for this on Calcite's board](https://issues.apache.org/jira/browse/IGNITE-18798) but nothing as of of now.
one hacky solution would be:
1. convert the substrait Expression.UDTLiteral into a VARBINARY/ByteString type. (the issue with this is that the Userdatatype.getsqlName would have to be set to sqlname.varbinary, otherwise the type check in calcite will fail)
2. and then when converting back, just check if …

feat: support UDT literals using bytestring/binary representation in calcite

---

.github/workflows/pr.yml

It seems that we have a lot of flakiness on the `Build and Test Java > Build with Gradle` step, and there's some suspicion that it might come from caching intermediate results and Jabel.
Adding `--rerun-tasks` seems like a good balance -- we don't disable cache completely (so we keep Maven artifacts) but we rebuild any unchanged dependencies to prevent such problems.

ci: disable task caches in gradle build

---

isthmus/src/main/java/io/substrait/isthmus/AggregateFunctions.java
isthmus/src/main/java/io/substrait/isthmus/expression/AggregateFunctionConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java
isthmus/src/test/java/io/substrait/isthmus/OptimizerIntegrationTest.java
isthmus/src/test/java/io/substrait/isthmus/PlanTestBase.java
isthmus/src/test/java/io/substrait/isthmus/expression/AggregateFunctionConverterTest.java

Some of the Calcite CoreRules might bring their own functions at a late stage, so I've decided to make the converter flexible enough and handle the superclass types correctly (since we already do a similar conversion to `APPROX_COUNT_DISTINCT` in the same spot).
Another alternative would be to improve the matchers and check if names match or if it's an `instanceof` the passing call -- today `signatures` is an `IdentityHashMap`, so it's really strict.

fix(isthmus): allow for conversion of plans containing Calcite aggregate functions

---

isthmus/src/main/java/io/substrait/isthmus/expression/SortFieldConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/WindowBoundConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/WindowFunctionConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/WindowRelFunctionConverter.java

We recently added POJOs for ConsistentPartitionWindowRel and WindowRelFunction. https://github.com/substrait-io/substrait-java/pull/231
The next step is starting to get isthmus support for it, so I went ahead and created WindowRelFunctionConverter so we can start using it to properly bind our window function calls.
It is heavily based on WindowFunctionConverter (although both the input and output changes - input from `RexOver` to `RexWinAggCall`, and output from `WindowFunctionInvocation` to `WindowRelFunctionInvocation`), so I extracted some converters to top-level classes to improve reusability.

feat(isthmus): add WindowRelFunctionConverter

---

core/src/main/java/io/substrait/function/ToTypeString.java
isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java
isthmus/src/test/java/io/substrait/isthmus/CustomFunctionTest.java
isthmus/src/test/resources/extensions/functions_custom.yaml

My attempt to take a stab at the `TODO` in the code:
```
// TODO: define up-converting matchers.
```
We've got here since we noticed that functions that have `list<any1>, any1` arguments wouldn't match `list<string>, string` without implementing a proper `CallConverter` as adapter:
- The `FunctionConverter` was not matching using `directMatchKey` since `list_any` != `list_str`.
- When falling back to the `leastRestrictive` logic, `list<string>` + `string` would also not agree, so no functions were returned.
I've kept the `leastRestrictive` logic intact, but added another fallback matcher that checks if all arguments will match (using the existent `isMatch` logic, which relies on [IgnoreNullableAndParameters](https://github.com/substrait-io/substrait-java/blob/main/isthmus/src/main/java/io/ …

feat(isthmus): add up-converting signature matchers, and coerce types to match 

---

core/src/main/java/io/substrait/dsl/SubstraitBuilder.java
isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java
isthmus/src/test/java/io/substrait/isthmus/CustomFunctionTest.java
isthmus/src/test/java/io/substrait/isthmus/PlanTestBase.java
isthmus/src/test/java/io/substrait/isthmus/WindowFunctionTest.java

When trying to bind a function such as `LAG(FP64, 1)`, due to LEAD/LAG having function variants that take a single input (`any`), the current matcher is using least restrictive matcher using types (FP64, I32), and ends up matching the wrong function.
The `matchCoerced` function added by https://github.com/substrait-io/substrait-java/pull/226 handles this case correctly, but because the least restrictive takes precedence, it doesn't use proper types.
Inverting the matchers didn't break any of the existing tests, and I added tests to cover the LEAD/LAG scenarios, so I think this is safe.

fix: match functions using coercion first instead of least restrictive

---

core/src/main/java/io/substrait/function/ToTypeString.java

According to the documentation the short types for IntervalDay and IntervalYear are iday and iyear
https://substrait.io/extensions/#function-signature-compound-names
https://github.com/substrait-io/substrait-java/issues/240

fix: correct function compound names for IntervalDay and IntervalYear #240

---

core/src/main/antlr/SubstraitType.g4
core/src/main/java/io/substrait/function/ParameterizedType.java
core/src/main/java/io/substrait/function/ParameterizedTypeCreator.java
core/src/main/java/io/substrait/function/ParameterizedTypeVisitor.java
core/src/main/java/io/substrait/function/ToTypeString.java
core/src/main/java/io/substrait/function/TypeExpression.java
core/src/main/java/io/substrait/function/TypeExpressionCreator.java
core/src/main/java/io/substrait/function/TypeExpressionVisitor.java
core/src/main/java/io/substrait/type/StringTypeVisitor.java
core/src/main/java/io/substrait/type/Type.java
core/src/main/java/io/substrait/type/TypeCreator.java
core/src/main/java/io/substrait/type/TypeVisitor.java
core/src/main/java/io/substrait/type/parser/ParseToPojo.java
core/src/main/java/io/substrait/type/proto/BaseProtoConverter.java
core/src/main/java/io/substrait/type/proto/BaseProtoTypes.java
core/src/main/java/io/substrait/type/proto/ParameterizedProtoConverter.java
core/src/main/java/io/substrait/type/proto/ProtoTypeConverter.java
core/src/main/java/io/substrait/type/proto/TypeExpressionProtoVisitor.java
core/src/main/java/io/substrait/type/proto/TypeProtoConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/IgnoreNullableAndParameters.java

feat(pojo): wire in PrecisionTimestamp and PrecisionTimestampTZ
BREAKING CHANGE: ParameterizedTypeVisitor has new visit methods
BREAKING CHANGE: TypeExpressionVisitor has new visit methods
BREAKING CHANGE: TypeVisitor has new visit methods
BREAKING CHANGE: BaseProtoTypes has new visit methods

chore: update to substrait 0.48.0

---

core/src/main/java/io/substrait/dsl/SubstraitBuilder.java
core/src/main/java/io/substrait/relation/ProtoRelConverter.java
core/src/main/java/io/substrait/relation/RelProtoConverter.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelVisitor.java
isthmus/src/test/java/io/substrait/isthmus/FetchTest.java

FetchRels with no count set could not be distinguished from FetchRels
with count set to 0.
To account for this, the spec now uses -1 as a sentinel value for this.
feat: new limit and offset methods on SubstraitBuilder

fix: handle LIMIT ALL queries using sentinel value in FetchRel::count

---

build.gradle.kts
core/build.gradle.kts
core/src/main/java/io/substrait/extension/SimpleExtension.java
core/src/main/java/io/substrait/type/YamlRead.java
gradle.properties
isthmus/build.gradle.kts
isthmus/src/main/java/io/substrait/isthmus/expression/FieldSelectionConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java
readme.md

Depend on slf4j-api instead of the slf4j-jdk14 logging framework. This allows consumers to select their preferred logging framework at deployment time by adding an appropriate SLF4J provider to their runtime classpath.
If no SLF4J provider is available at runtime, no logging output will be produced. The code still functions as expected.
The isthmus CLI command continues to log using java.util.logging by including the slf4j-jdk14 provider in its runtime classpath.

feat: allow deployment time selection of logging framework #243

---

.github/workflows/pr.yml
.github/workflows/release.yml

https://github.com/actions/setup-java/blob/main/README.md
AdoptOpenJDK is obsolete.  Use Temurin instead.

build: use Temurin jdk

---

.editorconfig
core/build.gradle.kts
isthmus/build.gradle.kts

ANTLR had a breaking change in its serialization format between 4.9 and 4.10+, meaning libraries that depend on one are incompatible with libraries that depend on another.
Spark (until Spark 4.x) depends on ANTRL 4.9, so this project bumping ANTLR 4.10+ made it impossible to use both Spark and substrait-java in the same project.
Shadowing and relocating the ANTLR dependency removes the issues with incompatibility since substrait-spark's ANTLR is now independent of any other ANTLRs.

chore: shadow ANTLR dependency

---

.github/workflows/pr.yml

This change modifies the pull request build definition so that previous builds of a pull request are cancelled when a new change is pushed. This avoids redundant pull request builds continuing to run to completion and wasting build resources.

ci: cancel in-progress build on PR update

---

.github/workflows/pr.yml
.github/workflows/release.yml

Actions based on Node versions lower than Node 20 are deprecated. See:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

ci: update deprecated GitHub actions

---

ci/release/dry_run.sh
ci/release/run.sh

Basically reverts https://github.com/substrait-io/substrait-java/pull/175/files.
That pin causes an issue, see e.g. https://github.com/semantic-release/release-notes-generator/issues/655#issuecomment-2143737739
Confirmed locally that before this change `./ci/release/dry-run.sh` fails with the same error as seen [here](https://github.com/substrait-io/substrait-java/actions/runs/9334990717/job/25694163852), after it works:
```
[4:25:06 PM] [semantic-release] › ✔  Published release 1.0.0 on default channel
[4:25:06 PM] [semantic-release] › ℹ  Release note for version 1.0.0:
* Substrait FP32 is now mapped to Calcite REAL instead of FLOAT
* Calcite FLOAT is now mapped to Substrait FP64 instead of FP32
In Calcite, the Sql Type Names DOUBLE and FLOAT correspond to FP64, and REAL corresponds to …
```

ci: stop pinning conventionalcommits

---

isthmus-cli/build.gradle.kts
isthmus/build.gradle.kts

- Remove concrete slf4j-jdk14 provider dependency from isthmus.
- Add concrete slf4j-jdk14 provider dependency to isthmus-cli.
Library components should only depend on slf4j-api, allowing consumers to select an appropriate concrete logging provider implementation. Being a self-contained (CLI) application, isthmus-cli can depend on a specific SLF4J provider.

fix(isthmus): correct SLF4J dependency

---

isthmus/src/main/java/io/substrait/isthmus/SubstraitTypeSystem.java
isthmus/src/main/java/io/substrait/isthmus/TypeConverter.java
isthmus/src/test/java/io/substrait/isthmus/CalciteTypeTest.java

feat(isthmus): support PrecisionTimestamp in isthmus

---

.github/workflows/pr.yml
build.gradle.kts
core/build.gradle.kts
gradle.properties
isthmus-cli/build.gradle.kts
isthmus/build.gradle.kts

Continue build on vulnerability detection.
Update protobuf dependency to address vulnerabilities:
- CVE-2022-25647
- CVE-2022-3509
- CVE-2022-3510
- CVE-2022-3171

build: add vulnerability scan to PR build

---

core/src/main/java/io/substrait/relation/ProtoRelConverter.java
core/src/main/java/io/substrait/relation/VirtualTableScan.java
core/src/test/java/io/substrait/relation/VirtualTableScanTest.java
core/src/test/java/io/substrait/type/proto/AggregateRoundtripTest.java
core/src/test/java/io/substrait/type/proto/ExtensionRoundtripTest.java
core/src/test/java/io/substrait/type/proto/ReadRelRoundtripTest.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelVisitor.java

VirtualTableScan in Substrait is expected to contain both a NamedSchema (field names in dfs form and types) like any other read rel, plus the actual data rows. However substrait-java was ignoring the types of the NamedSchema, instead grabbing type info from the first row of the data. This however is not always sufficient since the data can contain varying nullability row-by-row.
This also just simplifies VirtualTableScan and makes it behave more like one would expect by looking at the Substrait spec as well as other ReadRels

fix: set VirtualTableScan schema explicitly

---

core/src/main/java/io/substrait/type/TypeVisitor.java

By marking the function as @Deprecated and providing a default implementation makes users code a lot cleaner.
Directly implementations of the interface previously would need to implement these methods and cope with the Deprecation warning.
With this change if they are using it, no problems; but they are not obliged to implement it.

feat: deprecate Timestamp and TimestampTZ visit functions

---

core/src/main/java/io/substrait/expression/AggregateFunctionInvocation.java
core/src/main/java/io/substrait/expression/Expression.java
core/src/main/java/io/substrait/expression/ExpressionCreator.java
core/src/main/java/io/substrait/expression/FunctionOption.java
core/src/main/java/io/substrait/expression/proto/ExpressionProtoConverter.java
core/src/main/java/io/substrait/expression/proto/ProtoExpressionConverter.java
core/src/main/java/io/substrait/extendedexpression/ProtoExtendedExpressionConverter.java
core/src/main/java/io/substrait/relation/ConsistentPartitionWindow.java
core/src/main/java/io/substrait/relation/ProtoAggregateFunctionConverter.java
core/src/main/java/io/substrait/relation/ProtoRelConverter.java
core/src/main/java/io/substrait/relation/RelProtoConverter.java
core/src/test/java/io/substrait/type/proto/AggregateRoundtripTest.java
core/src/test/java/io/substrait/type/proto/ConsistentPartitionWindowRelRoundtripTest.java

[Options](https://substrait.io/expressions/scalar_functions/#options) were supported in the Java immutables but in most cases dropped when converting into protobuf
This
- fixes the protobuf conversion,
- adds a builder for FunctionOption
- adds a ExpressionCreator functions with options
- does some refactoring

fix: properly support Options for Scalar/Aggregate/Window functions

---

core/src/main/java/io/substrait/extension/AdvancedExtension.java
core/src/main/java/io/substrait/relation/ProtoRelConverter.java
core/src/main/java/io/substrait/relation/extensions/EmptyOptimization.java
core/src/test/java/io/substrait/relation/ProtoRelConverterTest.java
core/src/test/java/io/substrait/type/proto/ExtensionRoundtripTest.java

Bump substrait submodule to latest (0.52.0) and address the changes

chore: update to substrait 0.52.0

---

core/src/main/java/io/substrait/relation/ProtoRelConverter.java

I have a need to override some of the behavior in [ProtoRelConverter.java](https://github.com/substrait-io/substrait-java/compare/main...bvolpato:open-proto-rel-converter?expand=1#diff-dd48c750d05998223daf061d1d409a5691a8e3c22e93cf68467f393a062b785c)'s `newExtensionTable`, but today I can't because the class was designed to be all private.
I'd like to make that open if possible, to allow easily extending it instead of having to duplicate any code. I'm aware that there are some extension points / customization entries such as `detailFromExtensionTable`, but that signature isn't enough to have roundtrip-able leafs, because I can only derive the schema from the `Rel` itself, not from the data packed in the `Any` instance.

feat: opening ProtoRelConverter for extension

---

core/src/main/java/io/substrait/expression/Expression.java
core/src/test/java/io/substrait/type/proto/IfThenRoundtripTest.java

Recently had some nullability issues with Calcite coming from the SQL:
```
CASE WHEN record_type = 'abc' THEN
field_a
ELSE
''
END
```
Because the `else` part is a literal, `nullable` was false, but it wasn't actually true, as `field_a` is in fact nullable.
Calcite would fail assertions because of this mismatch:
```
rpc error: code = Internal desc = Cannot add expression of different type to set:
set type is RecordType(VARCHAR NOT NULL $f30, VARCHAR $f10) NOT NULL
expression type is RecordType(VARCHAR $f3, VARCHAR $f1) NOT NULL
set is org.apache.calcite.plan.volcano.RelSet@6624a103
expression is LogicalSort(sort0=[$1], dir0=[DESC], fetch=[5])
...
Type mismatch:
rowtype of original rel: RecordType(VARCHAR NOT NULL $f30, VARCHAR $f10) NOT NULL
rowtype of new rel: RecordType(VARCHAR $f3, …
```

fix(core): if-then expression should be nullable if any 'then' is nullable

---

core/src/main/java/io/substrait/relation/ConsistentPartitionWindow.java
core/src/test/java/io/substrait/type/proto/ConsistentPartitionWindowRelRoundtripTest.java

We've caught a problem where the `deriveRecordType` was very inconsistent with Calcite's `RowType`, and debugging those closely, Substrait was inconsistently adding the partition expression as part of the record type, which doesn't make sense (I mean in general, there might be cases that you are outputting the partition field).
I've fixed the `deriveRecordType` method to output based on the `windowFunctions` instead, and added a test that validates whether the types are still the expected after the round-trip, for the original case and added one new plan that had 2 distinct aggregations.

fix(core): row type should output the window function aggregation results

---

isthmus/src/main/java/io/substrait/isthmus/expression/WindowFunctionConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/WindowRelFunctionConverter.java

This to fix https://github.com/substrait-io/substrait-java/issues/290

feat(isthmus): allow WindowFunctionConverter to use a non-default TypeConverter

---

spark/src/main/resources/spark.yml
spark/src/main/scala/io/substrait/spark/SparkExtension.scala
spark/src/main/scala/io/substrait/spark/expression/FunctionMappings.scala
spark/src/main/scala/io/substrait/spark/expression/ToSparkExpression.scala
spark/src/test/scala/io/substrait/spark/TPCDSPlan.scala

The Spark query optimiser injects an internal function (MakeDecimal) when numeric literals appear in a query. This commit adds support for this, which drastically improves the pass rate for the TPC-DS test suite.

feat(spark): add MakeDecimal support

---

spark/src/main/scala/io/substrait/spark/logical/ToLogicalPlan.scala
spark/src/main/scala/io/substrait/spark/logical/ToSubstraitRel.scala
spark/src/test/scala/io/substrait/spark/TPCHPlan.scala

Add missing support for the ‘offset’ clause in the spark module.

feat(spark): support for FetchRel offset field

---

spark/src/main/scala/io/substrait/spark/ToSubstraitType.scala
spark/src/test/scala/io/substrait/spark/TPCDSPlan.scala

Add support for converting Boolean spark to substrait type. Enables two more successful TPC-DS tests.

feat(spark): support conversion of boolean types

---

spark/src/main/scala/io/substrait/spark/expression/FunctionMappings.scala
spark/src/test/scala/io/substrait/spark/TPCDSPlan.scala

Add support for the <=> operator (NULL safe equals) which gets generated by the spark optimiser for certain queries.
Enables three more successful TPC-DS tests.

feat(spark): map from EqualNullSafe fn to is_not_distinct_from

---

spark/.scalafmt.conf
spark/build.gradle.kts
spark/src/main/scala/io/substrait/spark/ToSubstraitType.scala
spark/src/main/scala/io/substrait/spark/expression/FunctionConverter.scala
spark/src/main/scala/io/substrait/spark/expression/IgnoreNullableAndParameters.scala
spark/src/main/scala/io/substrait/spark/expression/ToSparkExpression.scala
spark/src/main/scala/io/substrait/spark/expression/ToSubstraitExpression.scala
spark/src/main/scala/io/substrait/spark/expression/ToSubstraitLiteral.scala
spark/src/main/scala/io/substrait/spark/logical/ToLogicalPlan.scala
spark/src/main/scala/io/substrait/spark/logical/ToSubstraitRel.scala
spark/src/test/scala/io/substrait/spark/TPCDSPlan.scala
spark/src/test/scala/io/substrait/spark/TPCHPlan.scala

Add lint checking to the Scala code in the Spark module.
All other changes in this commit are the formatting changes created by the linter.

refactor: enable Spotless for Scala code

---

spark/src/main/scala/io/substrait/spark/expression/FunctionMappings.scala
spark/src/main/scala/io/substrait/spark/expression/ToSubstraitExpression.scala
spark/src/test/scala/io/substrait/spark/TPCDSPlan.scala

Add mappings for upper/lower/concat/coalesce

feat(spark): enable some missing string functions

---

spark/src/main/scala/io/substrait/spark/ToSubstraitType.scala
spark/src/main/scala/io/substrait/spark/logical/ToLogicalPlan.scala
spark/src/main/scala/io/substrait/spark/logical/ToSubstraitRel.scala
spark/src/test/scala/io/substrait/spark/RelationsSuite.scala

The other direction (Spark -> Substrait) was already supported, but this adds Substrait -> Spark and enables round-trip testing.
Also fixes LocalRelation -> VirtualTableScan for rows containing null values.

feat(spark): convert VirtualTableScan to LocalRelation 

---

spark/src/main/scala/io/substrait/spark/logical/ToLogicalPlan.scala
spark/src/test/scala/io/substrait/spark/TPCDSPlan.scala

Fix the logic for deriving whether each output column of the expand relation is nullable or not.
If one or more of the projections can assign null to the column, then it must be defined as nullable.

fix(spark): output columns of expand relation

---

spark/src/main/resources/spark.yml
spark/src/main/scala/io/substrait/spark/ToSubstraitType.scala
spark/src/main/scala/io/substrait/spark/expression/FunctionMappings.scala
spark/src/main/scala/io/substrait/spark/expression/ToSparkExpression.scala
spark/src/main/scala/io/substrait/spark/expression/ToSubstraitExpression.scala
spark/src/test/scala/io/substrait/spark/TPCDSPlan.scala

Adds support in the spark module for 8-bit and 16-bit integer types and for some bitwise functions. The catalyst optimizer generates expressions using these for certain query types.
Note that `shift_right` (and other bit shifting functions) might want to be considered for the core substrait function catalog, but it has been added here (temporarily?) as spark extension pending a longer term discussion/decision on their wider utility.

feat(spark): bitwise functions

---

spark/src/main/scala/io/substrait/debug/RelToVerboseString.scala
spark/src/main/scala/io/substrait/spark/SparkExtension.scala
spark/src/main/scala/io/substrait/spark/expression/FunctionConverter.scala
spark/src/main/scala/io/substrait/spark/expression/FunctionMappings.scala
spark/src/main/scala/io/substrait/spark/expression/ToAggregateFunction.scala
spark/src/main/scala/io/substrait/spark/expression/ToScalarFunction.scala
spark/src/main/scala/io/substrait/spark/expression/ToWindowFunction.scala
spark/src/main/scala/io/substrait/spark/logical/ToLogicalPlan.scala
spark/src/main/scala/io/substrait/spark/logical/ToSubstraitRel.scala
spark/src/main/scala/io/substrait/utils/Util.scala
spark/src/test/scala/io/substrait/spark/TPCDSPlan.scala
spark/src/test/scala/io/substrait/spark/WindowPlan.scala

To support the OVER clause in SQL
This fixes some of the TPC-DS tests.

feat(spark): add Window support

---

core/src/main/java/io/substrait/expression/AbstractExpressionVisitor.java
core/src/main/java/io/substrait/expression/Expression.java
core/src/main/java/io/substrait/expression/ExpressionCreator.java
core/src/main/java/io/substrait/expression/ExpressionVisitor.java
core/src/main/java/io/substrait/expression/proto/ExpressionProtoConverter.java
core/src/main/java/io/substrait/expression/proto/ProtoExpressionConverter.java
core/src/main/java/io/substrait/relation/ExpressionCopyOnWriteVisitor.java
core/src/main/java/io/substrait/type/TypeCreator.java
core/src/main/java/io/substrait/type/proto/ProtoTypeConverter.java
spark/src/main/scala/io/substrait/debug/ExpressionToString.scala
spark/src/main/scala/io/substrait/spark/ToSubstraitType.scala
spark/src/main/scala/io/substrait/spark/expression/ToSparkExpression.scala
spark/src/main/scala/io/substrait/spark/expression/ToSubstraitLiteral.scala
spark/src/main/scala/io/substrait/utils/Util.scala
spark/src/test/scala/io/substrait/spark/TypesAndLiteralsSuite.scala

45d938700c8f9208e378e20be096a88a78289783 adds support for EmptyMap into `core` - if preferred, I can split that off into its own PR
ea7bdb16bc726e71c7eff531f2b3841e09f0106b adds support for bunch of types and literals into substrait-spark, as well as testing for all of the currently supported types
c43f3991e7d51927aeb305e2836ffaaa70ed0a12 adds Byte and Short (taken from #309, thanks @andrew-coleman - this just so that should be fine to merge these in either order and we'll have tests setup fully)

feat(spark): add support for more types and literals (binary, list, map, intervals, timestamps)

---

core/src/main/java/io/substrait/relation/Expand.java
spark/src/main/scala/io/substrait/spark/SparkExtension.scala
spark/src/main/scala/io/substrait/spark/logical/ToLogicalPlan.scala
spark/src/main/scala/io/substrait/spark/logical/ToSubstraitRel.scala
spark/src/test/scala/io/substrait/spark/SubstraitPlanTestBase.scala

In the Expand relation, the record type was being calculated incorrectly, leading to errors when round-tripping to protobuf and back.

fix(spark): incorrect deriveRecordType() for Expand

---

spark/src/main/scala/io/substrait/spark/expression/ToSparkExpression.scala
spark/src/test/scala/io/substrait/spark/TPCDSPlan.scala

When casting a date type to a string, Spark requires that a timezone is specified, otherwise it will not resolve the logical plan.
The timezone is ignored for non-date/time values.

fix(spark): casting date/time requires timezone

---

core/src/main/java/io/substrait/expression/Expression.java
spark/src/main/scala/io/substrait/spark/expression/ToAggregateFunction.scala

feat(pojo): add UNSPECIFIED value to AggregationPhase enum

---

.github/workflows/pr.yml

The `ghcr.io/google/osv-scanner:latest` docker image was updated to `v2.0.0-beta1`.
This breaks the build with the error:
`Failed to parse SBOM "/bom.json" with error: could not determine extractor suitable to this file`
This commit pins the image tag to last working release `v1.9.2`

chore(spark): pin osv-scanner to v.1.9.2

---

isthmus/src/test/java/io/substrait/isthmus/TpcdsQueryNoValidation.java
isthmus/src/test/resources/tpcds/queries/72.sql

According to a related [Calcite issue](https://issues.apache.org/jira/browse/CALCITE-304), TPCDS query 72 uses Oracle-specific syntax for date addition, which defaults to days as the time unit when a numeric value is added to a date. A more standards-compliant form is to explicitly specify the time unit as an interval.

fix(isthmus): more standard SQL for TPCDS query 72

---

isthmus/src/main/java/io/substrait/isthmus/SubstraitRelNodeConverter.java
isthmus/src/test/java/io/substrait/isthmus/ComplexSortTest.java

This PR adds support for expressions in Sort (today, only input references are supported https://github.com/substrait-io/substrait-java/issues/192). 
This PR uses Calcite's `relbuilder.sort(rexNodes)` rather than computing `RelFieldCollation` (which required input references only). Calcite then makes sure to expand the Sort into a `LogicalSort` and a `LogicalProject` to evaluate expressions if needed (an additional `LogicalProject` is applied which acts like a remap to remove any introduced fields to preserve the same output).
```sql
SELECT foo FROM bar ORDER BY foo
```
```swift
LogicalSort(sort0=[$0], dir0=[ASC])
TableScan(table=[bar])
```
```sql
SELECT foo FROM bar ORDER BY foo::int + 1 DESC NULLS LAST
```
```swift
LogicalProject(foo=[$0])
LogicalSort(sort0=[$1], dir0=[DESC-nulls-last]) …
```

fix(isthmus): support expressions in Sort

---

.github/workflows/pr.yml
isthmus-cli/build.gradle.kts

Fixes https://github.com/substrait-io/substrait-java/issues/331
`-H:DynamicProxyConfigurationFiles=proxies.json` is interpreted based on the _cwd_, so it ends up being environment dependent.
The current change disambiguates/makes the path absolute for the module that defines the config.
cc @andrew-coleman that came up with the symlink approach.

build: fix flaky native build

---

core/build.gradle.kts
isthmus/build.gradle.kts

Currently, both the `isthmus` and `core` projects are declaring all dependencies as `implementation` dependencies. Gradle has two types of dependencies `api` and `implementation` dependencies. From the Gradle documentation:
> The `api` configuration should be used to declare dependencies which are exported by the library API, whereas the `implementation` configuration should be used to declare dependencies which are internal to the component.
https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation
For the [`core`](https://github.com/substrait-io/substrait-java/tree/main/core) project some of the protobuf Java classes are part of the Substrait Java API, e.g. `com.google.protobuf.ByteString` is exposed as part of the …

build: correctly declare api dependencies

---

core/src/main/java/io/substrait/relation/AbstractReadRel.java
core/src/main/java/io/substrait/relation/ProtoRelConverter.java
core/src/main/java/io/substrait/relation/RelProtoConverter.java
core/src/test/java/io/substrait/type/proto/ReadRelRoundtripTest.java

ReadRel spec contains a BestEffortFilter expression that is ignored by the Java ProtoRel and RelProto converter.
Adding support to it, similarly to the existing Filter expression.
Thanks

feat(pojo): support best_effort_filter on ReadRel messages

---

isthmus/src/main/java/io/substrait/isthmus/expression/ExpressionRexConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/LiteralConverter.java
isthmus/src/test/java/io/substrait/isthmus/CalciteLiteralTest.java

RexLiteral day/time intervals were converted to Substrait using their scale. Despite all day/time interval RexLiteral created from SQL by Calcite having a (default) scale of 6, their value is always in milliseconds. This resulted in intervals generated by Calcite from SQL being wrong by a factor of 1000 seconds.
This change treats day/time interval RexLiteral values as milliseconds regardless of their claimed scale.
Closes #327

fix(isthmus): sql day/time interval conversion

---

spark/src/main/scala/io/substrait/debug/ExpressionToString.scala
spark/src/main/scala/io/substrait/debug/RelToVerboseString.scala
spark/src/main/scala/io/substrait/spark/ToSubstraitType.scala
spark/src/main/scala/io/substrait/spark/expression/ToSparkExpression.scala
spark/src/main/scala/io/substrait/spark/expression/ToSubstraitExpression.scala
spark/src/main/scala/io/substrait/spark/logical/ToLogicalPlan.scala
spark/src/main/scala/io/substrait/spark/logical/ToSubstraitRel.scala
spark/src/test/scala/io/substrait/spark/SubstraitPlanTestBase.scala
spark/src/test/scala/io/substrait/spark/TPCDSPlan.scala
spark/src/test/scala/io/substrait/spark/TPCHPlan.scala

For certain filter expressions that embed subqueries, the Spark optimiser replaces these with a Join relation of type ‘ExistenceJoin’. This internal join type does not map directly to any standard SQL join type, or Substrait join type.
To address this, it needs to be converted to a substrate ‘InPredicate’ within a filter condition.

feat(spark): support ExistenceJoin internal join type

---

isthmus/src/main/java/io/substrait/isthmus/SubstraitToCalcite.java
isthmus/src/test/java/io/substrait/isthmus/SubstraitToCalciteTest.java

Isthmus currently only supports converting a Substrait `Rel` into a Calcite `RelNode` losing the final column names which are encoded in the Substrait `Plan.Root` and which should be converted into a Calcite `RelRoot`.
This PR adds a `convert()` method for converting a Substrait `Plan.Root` into a Calcite `RelRoot` preserving the final column names.
Currently, substrait-java does not support DML/DDL relations like`WriteRel` so the conversion may have to be revisited once support for DML/DDL relations is being added.

feat(isthmus): support converting Substrait Plan.Root to Calcite RelRoot

---

spark/src/main/scala/io/substrait/spark/logical/ToLogicalPlan.scala
spark/src/main/scala/io/substrait/spark/logical/ToSubstraitRel.scala
spark/src/test/scala/io/substrait/spark/RelationsSuite.scala

Add support for the Spark OneRowRelation, which is the leaf node that represents selects without a from clause.
A follow-on PR will use this to aid testing.

feat(spark): support SELECT without FROM clause

---

core/src/main/java/io/substrait/expression/proto/ExpressionProtoConverter.java
core/src/main/java/io/substrait/extension/AdvancedExtension.java
core/src/main/java/io/substrait/relation/RelProtoConverter.java
core/src/main/java/io/substrait/relation/ToProto.java
core/src/main/java/io/substrait/relation/extensions/EmptyDetail.java
core/src/main/java/io/substrait/relation/extensions/EmptyOptimization.java
core/src/main/java/io/substrait/type/proto/TypeProtoConverter.java
core/src/test/java/io/substrait/relation/utils/StringHolder.java
isthmus/build.gradle.kts
isthmus/src/test/java/io/substrait/isthmus/RelExtensionRoundtripTest.java
isthmus/src/test/resources/extensions/substrait.proto

An emergent pattern with Extension relations is for users to include
Substrait messages within the detail field.
To convert these Substrait messages, users need to access to conversion
machinery within the code for converting details. This PR enables that
by modifying the ToProto interface.
BREAKING CHANGE: interface method ToProto#toProto now consumes a RelProtoConverter
BREAKING CHANGE: constructor for ExpressionProtoConverter now requires a RelProtoConverter specifically

feat: allow for more ergonomic conversion of Extension relations

---

isthmus/src/main/java/io/substrait/isthmus/SqlConverterBase.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitTypeSystem.java
isthmus/src/test/java/io/substrait/isthmus/PlanTestBase.java

BREAKING CHANGE: SQL parsing no longer uses the default Calcite type system

fix: use SubstraitTypeSystem when parsing SQL

---

isthmus-cli/src/main/java/io/substrait/isthmus/cli/IsthmusEntryPoint.java
isthmus/src/main/java/io/substrait/isthmus/FeatureBoard.java
isthmus/src/main/java/io/substrait/isthmus/SqlConverterBase.java

Adds a command line argument to Isthmus CLI to allow specifying Calcite's "unquoted casing" policy.
I want to add Substrait based sqllogictests to [DataFusion](https://github.com/apache/datafusion), converting the SQL to Substrait through Isthmus.
The main blocker right now is that Isthmus generates Substrait plans with uppercase tables and columns, whereas DataFusion normalizes to lowercase by default.

feat: Add `unquotedcasing` option to Isthmus CLI

---

spark/src/main/scala/io/substrait/spark/expression/ToSubstraitExpression.scala
spark/src/test/scala/io/substrait/spark/LocalFiles.scala
spark/src/test/scala/io/substrait/spark/TPCDSPlan.scala

For a certain types of queries, the spark optimiser will rewrite the plan to create structs of merged sub-queries.
These plans don’t convert directly to substrait.  This commit provides a matcher for these structures and converts them back to their original form before translating them to Substrait.

feat(spark): support merged structures

---

core/src/main/java/io/substrait/dsl/SubstraitBuilder.java
core/src/test/java/io/substrait/type/proto/ReadRelRoundtripTest.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitToCalcite.java
isthmus/src/main/java/io/substrait/isthmus/expression/ExpressionRexConverter.java
isthmus/src/test/java/io/substrait/isthmus/RelExtensionRoundtripTest.java
isthmus/src/test/java/io/substrait/isthmus/SubstraitExpressionConverterTest.java

Currently, the Substrait to Calcite mappings to not support scalar subqueries like the follow SQL example:
```sql
select 
n_name 
from 
tpch.tiny.nation 
where 
n_regionkey = (
select r_regionkey from tpch.tiny.region where r_name = 'EUROPE')
```
This PR adds support for mapping scalar subqueries from Substrait into Calcite and adds a test case showing that it works now.
Additionally:
- it changes `RelCreator` to be created with a list of CREATE SQL statements to initialize the schema of the `RelBuilder`
- the previous change requires `RelCreator` to extend `SqlConverterBase` so that we can reuse the `registerCreateTables()` method
- in `SubstraitExpressionConverterTest` it gets the `ExpressionRexConverter` from `SubstraitRelNodeConverter` in order to make sure the …

feat(isthmus): add support for scalar subqueries

---

.gitignore
build.gradle.kts

When I run `./gradlew clean build` on my local clone I constantly see Spotless tripping up on files in the `build` folder no longer existing which means I have to run the command multiple times. This suggests to me that the `targetExclude` configuration does not work as expected.
Instead this PRs configures the `target` to format every `*.java` file within any of the `src/*/java/**` directories which works more reliably and achieves the same goal as the current configuration.
This PR also adds `.metals` to the `.gitignore` for the VS Code users among us which uses metals for the Scala code.

build: make spotless run more reliably

---

isthmus-cli/src/main/java/io/substrait/isthmus/cli/IsthmusEntryPoint.java
isthmus-cli/src/test/java/io/substrait/isthmus/cli/IsthmusEntryPointTest.java
isthmus/src/main/java/io/substrait/isthmus/FeatureBoard.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelVisitor.java
isthmus/src/test/java/io/substrait/isthmus/ProtoPlanConverterTest.java

BREAKING CHANGE: removed CrossJoinPolicy from FeatureBoard

feat(isthmus): always emit Cross relation when possible

---

core/src/main/java/io/substrait/relation/ProtoRelConverter.java
spark/src/main/scala/io/substrait/spark/logical/ToLogicalPlan.scala
spark/src/main/scala/io/substrait/spark/logical/ToSubstraitRel.scala
spark/src/test/scala/io/substrait/spark/TPCDSPlan.scala

A number of the TPC-DS tests were failing because the query contains multiple aliases to the same expression, causing a potential mismatch in the reference index.  Although the plans were equivalent, the substrait POJO comparison failed. This commit uses the `hint` field of the Rel message to store the alias names, and restore them back to the Spark plan to match the original.

fix(spark): enable aliased expressions to round-trip

---

isthmus/src/main/java/io/substrait/isthmus/expression/ExpressionRexConverter.java
isthmus/src/test/java/io/substrait/isthmus/SubstraitExpressionConverterTest.java

When converting a Substrait plan back to Apache Calcite which contains a datetime subtract such as the one generated by SQL-to-Substrait code for TPC-H query no. 1 the mapping fails with a `java.lang.ArrayIndexOutOfBoundsException` because the Substrait-to-Calcite mapping code relies on Calcite's type inference for determining the return type of the `subtract` function call. 
Since the Substrait plan contains an explicitly return type in this case for this function call we can simply provide the return type explicitly to Calcite and avoid using the return type inference.
This PRs provides the function return type from the Substrait plan to Calcite and adds a test case for verifying that the expression conversion no longer throws an Exception and sets the function return type correctly in …

fix(isthmus): use explicit return type for scalar function expressions

---

core/src/main/java/io/substrait/relation/ProtoRelConverter.java
core/src/main/java/io/substrait/relation/RelProtoConverter.java
isthmus/src/main/java/io/substrait/isthmus/SqlToSubstrait.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelVisitor.java
isthmus/src/test/java/io/substrait/isthmus/NameRoundtripTest.java
isthmus/src/test/java/io/substrait/isthmus/PlanTestBase.java
isthmus/src/test/java/io/substrait/isthmus/Substrait2SqlTest.java

In the SubstraitRelVisitor, RelRoots must be converted to Plan.Roots in order to
ensure that names are handled correctly.
BREAKING CHANGE: converting a Calcite RelRoot no longer produces a Substrait Rel

feat(isthmus): convert Calcite RelRoot to Substrait Plan.Root

---

core/src/main/java/io/substrait/relation/files/FileFormat.java
spark/src/main/scala/io/substrait/spark/logical/ToSubstraitRel.scala
spark/src/test/scala/io/substrait/spark/LocalFiles.scala

Round-trip testing was failing for query plans that involved reading files from the filesystem.
This was due to the conversion code instantiating objects directly rather than using the immutable builders. The round-trip object comparison was then failing. This commit fixes that by using the ImmutableFileFormat builders, and hence the generated equals() methods.

fix(spark): use ImmutableFileFormat builders

---

spark/src/main/scala/io/substrait/spark/logical/ToLogicalPlan.scala
spark/src/test/scala/io/substrait/spark/LocalFiles.scala

The `ToLogicalPlan` class constructor takes a SparkSession argument which must be supplied by the caller.
We can simplify the API by making this parameter optional, and defaulting to `SparkSession.builder().getOrCreate()`. The `LocalFiles.scala` test has been modified so that both usages get tested.
The need for this was triggered by invoking this API from Python code (pyspark).  Passing the SparkSession object from python involves accessing internal handles, which doesn’t make for a good user experience.

feat(spark): make SparkSession optional

---

core/src/main/java/io/substrait/expression/EnumArg.java
readme.md
spark/src/main/resources/spark.yml
spark/src/main/scala/io/substrait/spark/expression/Enum.scala
spark/src/main/scala/io/substrait/spark/expression/FunctionConverter.scala
spark/src/main/scala/io/substrait/spark/expression/FunctionMappings.scala
spark/src/main/scala/io/substrait/spark/expression/ToScalarFunction.scala
spark/src/main/scala/io/substrait/spark/expression/ToSparkExpression.scala
spark/src/main/scala/io/substrait/spark/expression/ToSubstraitExpression.scala
spark/src/main/scala/io/substrait/spark/logical/ToLogicalPlan.scala
spark/src/test/scala/io/substrait/spark/DateTimeSuite.scala
spark/src/test/scala/io/substrait/spark/TPCDSPlan.scala
spark/src/test/scala/io/substrait/spark/expression/YamlTest.scala

The date/time functions in Spark don’t map directly to the Substrait eqivalents. E.g.
- `date ± interval-days` are handled by the `DateAdd` & `DateSub` functions in Spark, but as a variant of the arithmetic `add` function in substrait.
- The date/time component extraction functions are all handled by different functions in Spark, but by a single `extract` function in Substrait with an `enum` argument to specify which component.
Neither of these could be handled using the existing function mapping capabilities in the `spark` module.
This commit exends this capability so that it can now handle these two scenarios in (I hope) a generic way.
I’ve added a few variants of the `extract` function - more can follow.
Adding this will give us 100% pass rate for all the TPC-DS querues.  The README is …

feat(spark): add some date functions

---

core/src/main/java/io/substrait/dsl/SubstraitBuilder.java
isthmus/src/main/java/io/substrait/isthmus/expression/EnumConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/ExpressionRexConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java
isthmus/src/test/java/io/substrait/isthmus/ExpressionConvertabilityTest.java
isthmus/src/test/java/io/substrait/isthmus/FunctionConversionTest.java

Currently, the Substrait to Calcite mappings only support mapping scalar functions with enum arguments for the `extract:req_ts` function which means it only supports the `extract` function with an enum argument and a timestamp but none of the other datetime extract functions defined in the default datetime extension.
This PR adds basic support for all datetime extract functions which are not using the indexing argument which indicates whether e.g. months should start to be counted from 0 instead of 1.
It is still a naive mapping from the enum values defined in the datetime extension YAML to Apache Calcite's `TimeUnitRange` enum which misses some of the Substrait enum values (e.g. `US_YEAR`, `PICOSECONDS`) or has spelling differences for some of the enum values (`ISOYEAR` vs. `ISO_YEAR`). …

fix(isthmus): support more datetime extract variants

---

isthmus/src/main/java/io/substrait/isthmus/SubstraitTypeSystem.java
isthmus/src/main/java/io/substrait/isthmus/expression/AggregateFunctionConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/ScalarFunctionConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/WindowFunctionConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/WindowRelFunctionConverter.java
isthmus/src/test/java/io/substrait/isthmus/FunctionConversionTest.java
isthmus/src/test/java/io/substrait/isthmus/TpcdsQueryNoValidation.java

The type matching used when mapping Calcite to Substrait expressions required parameters and return type of the concat function to be either all varchar or all string. Any mixing of types caused a failure.
This change relaxes the type matching to allow string types (varchar, char and string literal) to be used interchangeably.
Closes #69
Contributes to #105

fix(isthmus): concat of different string types

---

isthmus/src/test/java/io/substrait/isthmus/TpcdsQueryNoValidation.java

Other changes have allowed TPC-DS query 2 to be converted to Substrait without error. This query previously failed due to lack of support for rouding decimals.
This change enables the unit test for TPC-DS query 2.

chore(isthmus): enable working TPC-DS query test

---

gradle.properties
isthmus/build.gradle.kts
isthmus/src/test/java/io/substrait/isthmus/TpcdsQueryNoValidation.java

This version of Calcite improves support for nested window aggregation, which allows Isthmus to support several TPC-DS queries that were previously failing.

fix(isthmus): upgrade to Calcite 1.39.0

---

core/src/main/java/io/substrait/relation/Join.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelNodeConverter.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelVisitor.java
spark/src/main/scala/io/substrait/spark/logical/ToLogicalPlan.scala
spark/src/main/scala/io/substrait/spark/logical/ToSubstraitRel.scala

I noticed the Substrait specification has a couple more join types defined which were not supported yet by the substrait-java/core library. This PR adds support for these additional join types to substrait-java/core.
Additionally, it deprecates the old `JoinType` enum names `SEMI` and `ANTI` in order to be consistent with the Substrait specification names `LEFT_SEMI` and `LEFT_ANTI`.
This PR does neither add support for the new join types to the Isthmus mappings nor the Spark mappings.

feat: add new join types

---

core/src/main/java/io/substrait/extension/ExtensionCollector.java

When validating Substrait plans generated by substrait-java with the current substrait-validator (which is pretty out of date) the validator gives the following warning for all plans:
```
Warning (code 3005):
at plan.extensions[0].mapping_type<extension_function>.function_anchor:
use of anchor zero is discouraged, as references set to zero may be confused with "unspecified". (code 3005)
```
This can be easily fixed by assigning functionAnchor values starting from one instead of zero.

fix(core): start with functionAnchor one instead of zero

---

core/build.gradle.kts
core/src/main/java/io/substrait/plan/Plan.java

Fixes https://github.com/substrait-io/substrait-java/issues/411
This PR keeps the manifest files since they are still a good practice to keep around. But instead of relying on the specification version from the manifest for populating the Substrait plan version this PR adds Gradle code which generates a simple Java class `SubstraitVersion` with a constant `VERSION` containing the version number from git describe.
From #411 it looks like at least in some cases when calling the isthmus Java code from Python via JPype there is an issue accessing the manifest file or any other file packaged as a resource into the isthmus shadow JAR. Using a generated Java class avoids this issue since JPype seems to have no issues accessing Java classes.

fix(core): create and use SubstraitVersion Java class

---

build.gradle.kts
isthmus/src/main/java/io/substrait/isthmus/expression/EnumConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/ExpressionRexConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/FunctionMappings.java
isthmus/src/main/java/io/substrait/isthmus/expression/ScalarFunctionConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/ScalarFunctionMapper.java
isthmus/src/main/java/io/substrait/isthmus/expression/SubstraitFunctionMapping.java
isthmus/src/main/java/io/substrait/isthmus/expression/TrimFunctionMapper.java
isthmus/src/test/java/io/substrait/isthmus/PlanTestBase.java
isthmus/src/test/java/io/substrait/isthmus/StringFunctionTest.java
isthmus/src/test/java/io/substrait/isthmus/TpcdsQueryTest.java
isthmus/src/test/java/io/substrait/isthmus/TpchQueryTest.java
isthmus/src/test/java/io/substrait/isthmus/expression/AggregateFunctionConverterTest.java

This enables support for TPC-DS query 98.
Closes #399

feat(isthmus): support for SQL TRIM function

---

core/src/main/java/io/substrait/relation/ProtoRelConverter.java
core/src/test/java/io/substrait/relation/ProtoRelConverterTest.java

Most of the mappings were missing the hints. This PR re-uses the already existing `optionalHint` method and includes the hints for relations where this was missing. No other functional changes.

fix(core): convert hints in ProtoRelConverter

---

core/src/main/java/io/substrait/dsl/SubstraitBuilder.java
core/src/main/java/io/substrait/expression/EnumArg.java
core/src/main/java/io/substrait/expression/proto/ProtoExpressionConverter.java
core/src/main/java/io/substrait/extendedexpression/ExtendedExpression.java
core/src/main/java/io/substrait/extendedexpression/ProtoExtendedExpressionConverter.java
core/src/main/java/io/substrait/extension/SimpleExtension.java
core/src/main/java/io/substrait/plan/Plan.java
core/src/main/java/io/substrait/relation/ProtoRelConverter.java
core/src/main/java/io/substrait/relation/files/FileFormat.java
core/src/main/java/io/substrait/relation/files/FileOrFiles.java
core/src/main/java/io/substrait/type/NamedStruct.java
core/src/test/java/io/substrait/extendedexpression/ExtendedExpressionRoundTripTest.java
core/src/test/java/io/substrait/type/proto/AggregateRoundtripTest.java
core/src/test/java/io/substrait/type/proto/ConsistentPartitionWindowRelRoundtripTest.java
core/src/test/java/io/substrait/type/proto/LocalFilesRoundtripTest.java
core/src/test/java/io/substrait/type/proto/TestTypeRoundtrip.java
isthmus/src/main/java/io/substrait/isthmus/PreCalciteAggregateValidator.java
isthmus/src/main/java/io/substrait/isthmus/SqlExpressionToSubstrait.java
isthmus/src/main/java/io/substrait/isthmus/SqlToSubstrait.java
isthmus/src/main/java/io/substrait/isthmus/expression/CallConverters.java
isthmus/src/test/java/io/substrait/isthmus/FunctionConversionTest.java
spark/src/main/scala/io/substrait/spark/expression/ToSubstraitExpression.scala
spark/src/main/scala/io/substrait/spark/logical/ToSubstraitRel.scala

Some of the non-core code is directly importing and invoking the object factories that are generated at build time from the immutables annotations.  This commit changes the code to (where possible) use the parent class methods.

chore: avoid using generated immutables

---

.github/workflows/release.yml
core/build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
isthmus/build.gradle.kts
spark/build.gradle.kts

JReleaser expects to have the corresponding public key available when signing artifacts so that it can verify that the public key is published to known key registries. While publishing works without the public key, it outputs a warning message, which can cause confusion when viewing build logs.
This change disables JReleaser artifact signing and reverts to using Gradle's own signing plugin. This also provides a smoother migration path to an official Sonatype Gradle publishing plugin, if/when one becomes available in the future.
Gradle wrapper is also updated to the latest patch release.
Relates to #419

build: use Gradle signing instead of JReleaser

---

examples/substrait-spark/build.gradle.kts
examples/substrait-spark/src/main/java/io/substrait/examples/util/ExpressionStringify.java
examples/substrait-spark/src/main/java/io/substrait/examples/util/FunctionArgStringify.java
examples/substrait-spark/src/main/java/io/substrait/examples/util/SubstraitStringify.java
examples/substrait-spark/src/main/java/io/substrait/examples/util/TypeStringify.java
spark/build.gradle.kts

The substrait spark example was using a static outdated version of the substrait spark mappings. This PR changes the substrait spark example to always use the latest substrait spark mappings and updates the code according to the latest changes.
Additionally, it changes the substrait spark mapping Gradle build to declare the spark-core and spark-sql dependencies as `api` dependencies so we don't have to redeclare them for the substrait spark example. This also required to change the `java` Gradle plugin to the `java-library` Gradle plugin.

chore: update spark example to use latest substrait-spark

---

buildSrc/src/main/resources/substrait-pmd.xml
core/src/main/java/io/substrait/expression/proto/ExpressionProtoConverter.java
core/src/main/java/io/substrait/expression/proto/ProtoExpressionConverter.java
core/src/main/java/io/substrait/extension/SimpleExtension.java
core/src/main/java/io/substrait/relation/ProtoRelConverter.java
core/src/main/java/io/substrait/relation/RelProtoConverter.java
core/src/main/java/io/substrait/type/YamlRead.java
core/src/test/java/io/substrait/relation/utils/StringHolderHandlingProtoRelConverter.java
examples/substrait-spark/build.gradle.kts
isthmus-cli/src/main/java/io/substrait/isthmus/cli/RegisterAtRuntime.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelNodeConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/FunctionConverter.java
isthmus/src/main/java/io/substrait/isthmus/expression/ListSqlOperatorFunctions.java
isthmus/src/test/java/io/substrait/isthmus/AggregationFunctionsTest.java
isthmus/src/test/java/io/substrait/isthmus/CalciteLiteralTest.java
isthmus/src/test/java/io/substrait/isthmus/CustomFunctionTest.java
isthmus/src/test/java/io/substrait/isthmus/PlanTestBase.java
isthmus/src/test/java/io/substrait/isthmus/RelCreator.java
isthmus/src/test/java/io/substrait/isthmus/RelExtensionRoundtripTest.java
spark/src/main/scala/io/substrait/spark/logical/ToLogicalPlan.scala

replaces throwing a generic `RuntimeException` with a more specific exception like `IllegalStateException`, `IllegalArgumentException` or `UnsupportedOperationException`

style: replace RuntimeException with more specific exceptions

---

isthmus-cli/src/test/script/tpch_smoke.sh

- The tpch_smoke.sh script did not test all 22 TPC-H queries since they failed to convert previously.
- This simple fix to the test script avoids the issue of picocli confusing the comments in the SQL with CLI arguments by providing the SQL arguments last.
- Additionally, the progress we made in increasing TPC-H query conversion rate makes all 22 queries convert without throwing an exception.
fixes #86 
fixes #87

fix(isthmus-cli): fix tpch_smoke.sh test script

---

core/src/main/java/io/substrait/relation/RelCopyOnWriteVisitor.java
isthmus/src/main/java/io/substrait/isthmus/SqlToSubstrait.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelNodeConverter.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitRelVisitor.java
isthmus/src/main/java/io/substrait/isthmus/SubstraitToCalcite.java
isthmus/src/test/java/io/substrait/isthmus/DmlRoundtripTest.java
isthmus/src/test/java/io/substrait/isthmus/PlanTestBase.java

As discussed, splitting the PR https://github.com/substrait-io/substrait-java/pull/428 into dml and ddl parts. This PR is for dml support.
The class `SubstraitRelVisitor` now supports the following operations for the `TableModify` node:
- insert
- update
- delete

feat(core,isthmus): add dml support to SqlToSubstrait

---

.commitlintrc.js
.github/dependabot.yml

This PR adds a dependabot config for Gradle and Github Actions dependencies.
I tested it on my fork: https://github.com/nielspardon/substrait-java/pulls
I tried the git submodule config but that is limited in that it does not support further configuration to e.g. only update to tags so I would not use dependabot for the git submodule updates.
I had to modify the `commitlint` configuration to allow the dependabot PRs to bypass the commit linting. The reason is that dependabot PRs create commits where the commit body contains lines longer than 100 characters which is otherwise not allowed by the current `commitlint` config.

build: ignore dependabot commits during commitlint

---

bom/build.gradle.kts
build-logic/build.gradle.kts
build-logic/settings.gradle.kts
build.gradle.kts
core/build.gradle.kts
examples/substrait-spark/build.gradle.kts
gradle.properties
gradle/libs.versions.toml
isthmus-cli/build.gradle.kts
isthmus/build.gradle.kts
settings.gradle.kts
spark/build.gradle.kts

The way dependency versions are currently declared is not working well with dependabot. To make it easier for dependabot to detect the dependency versions I suggest to move the dependency versions into a [Gradle version catalog](https://docs.gradle.org/current/userguide/version_catalogs.html) (`libs.versions.toml`).
This PR moves both the dependency and Gradle plugin versions into a version catalog.

build: use Gradle version catalog for dependencies and plugins

---

gradle.properties

Current PR builds fail because of trashing of JVM GC. This PR sets the heap size to 1 gig.

build: increase jvm heap size

---

isthmus-cli/src/main/java/io/substrait/isthmus/cli/IsthmusEntryPoint.java
isthmus/src/main/java/io/substrait/isthmus/SqlToSubstrait.java
isthmus/src/test/java/io/substrait/isthmus/ApplyJoinPlanTest.java
isthmus/src/test/java/io/substrait/isthmus/KeyConstraintsTest.java
isthmus/src/test/java/io/substrait/isthmus/NameRoundtripTest.java
isthmus/src/test/java/io/substrait/isthmus/NestedStructQueryTest.java
isthmus/src/test/java/io/substrait/isthmus/PlanTestBase.java
isthmus/src/test/java/io/substrait/isthmus/ProtoPlanConverterTest.java
isthmus/src/test/java/io/substrait/isthmus/RelCopyOnWriteVisitorTest.java
isthmus/src/test/java/io/substrait/isthmus/SubqueryPlanTest.java
isthmus/src/test/java/io/substrait/isthmus/TpcdsQueryTest.java
isthmus/src/test/java/io/substrait/isthmus/TpchQueryTest.java

I noticed that #432 could benefit from this refactoring.
BREAKING CHANGE: deprecates SqlToSubstrait.execute()
- adds a new `convert()` method to `SqlToSubstrait` which converts a SQL statements string to a POJO `Plan` instead of a proto `Plan`
- deprecates the `execute()` method in `SqlToSubstrait` which converts a SQL statements string to a proto `Plan`
- changes any uses of `execute()` in the code to `convert()`
- removes the `@VisibleForTesting` annotation from `SqlToSubstrait.createSqlToRelConverter()` and `SqlToSubstrait.getBestExpRelRoot()` since they are not actually used in testing and makes them `protected` instead of package private
- adds `@VisibleForTesting` annotation to `SqlToSubstrait.sqlToRelNode()` which is actually still used in testing
- changes the `TpcdsQueryTest` and …

feat(isthmus): add method converting SQL to POJO Plan

---

.commitlintrc.js

I had copied and modified the regular expression from the https://github.com/substrait-io/substrait project which turns out to not work properly here and I forgot to escape the brackets.
I tested this one now and it works now.

build: fix commitlint ignore regex for dependabot

---

core/build.gradle.kts
isthmus-cli/build.gradle.kts

This fixes two Gradle warnings about the use of deprecated features which are planned to be removed in Gradle 10.

build: fix Gradle warnings

---

gradle/libs.versions.toml

This PR manually updates scalatest and scalatestplus-junit5 from 3.2.18 to 3.2.19 and the scalatestplus-junit5 dependency to the JUnit 5.13 version to be aligned with the JUnit version already being at 5.13.
The dependabot PR for scalatest unfortunately picked up a pre-release version of scalatest 3.3.0-SNAP4 (#479).

build(deps): bump scalatest and scalatestplus-junit5 from 3.2.18 to 3.2.19

---

spark/build.gradle.kts
spark/src/main/scala/io/substrait/spark/logical/ToLogicalPlan.scala

Enable the `-Xfatal-warnings` flag for the Scala compiler to turn warnings into errors (i.e. fail the build).
Suppress this warning for the case where the spark converter is handling deprecated substrait enum values in the Join relation. We still want the converter to hande this legacy value without throwing an exception.
Resolves https://github.com/substrait-io/substrait-java/issues/321

ci: handle warnings in compileScala as errors

---

core/src/main/java/io/substrait/extendedexpression/ProtoExtendedExpressionConverter.java
core/src/main/java/io/substrait/extension/DefaultExtensionCatalog.java
core/src/main/java/io/substrait/extension/SimpleExtension.java
core/src/main/java/io/substrait/plan/ProtoPlanConverter.java
core/src/main/java/io/substrait/relation/ProtoAggregateFunctionConverter.java
core/src/main/java/io/substrait/relation/ProtoRelConverter.java
core/src/test/java/io/substrait/TestBase.java
isthmus-cli/src/main/java/io/substrait/isthmus/cli/IsthmusEntryPoint.java
isthmus/src/main/java/io/substrait/isthmus/SqlConverterBase.java
isthmus/src/test/java/io/substrait/isthmus/CalciteCallTest.java
isthmus/src/test/java/io/substrait/isthmus/RelCopyOnWriteVisitorTest.java
spark/src/main/scala/io/substrait/spark/SparkExtension.scala

Provide convenient static instance of default ExtensionCollection
BREAKING CHANGE: removed SimpleExtension.loadDefaults

feat: introduce DefaultExtensionCatalog.DEFAULT_COLLECTION

---

build.gradle.kts

The `removeWildcardImports` configuration option was renamed to `forbidWildcardImports` in v8.0.0 of the Spotless Gradle plugin.
https://github.com/diffplug/spotless/releases/tag/gradle/8.0.0
This change uses the new named to avoid a build time warning.

build: config option renamed in spotless 8 plugin

---

isthmus/src/main/java/io/substrait/isthmus/OuterReferenceResolver.java
isthmus/src/test/java/io/substrait/isthmus/SubqueryPlanTest.java
isthmus/src/test/java/io/substrait/isthmus/TpcdsQueryTest.java

Previously a subquery nested within a project was explicitly disallowed when converting from Calcite to Substrait. This is because outer references were not correctly resolved within nested subqueries.
This change tracks outer references so they can be successfully resolved in subqueries nested within a project.
Closes #70

feat(isthmus): support subquery nested in project

---

gradle/libs.versions.toml
isthmus-cli/build.gradle.kts
isthmus-cli/src/main/java/io/substrait/isthmus/cli/RegisterAtRuntime.java

org.reflections:reflections is used to locate classes that need to be registered during the GraalVM native image build process. Reflections is no longer maintained and there have been no releases since 2021.
This change replaces reflections with classgraph, which is actively maintained.
Closes #532

build(isthmus-cli): use classgraph instead of reflections

---

spark/src/main/scala/io/substrait/spark/logical/ToLogicalPlan.scala
spark/src/test/scala/io/substrait/spark/HiveTableSuite.scala
spark/src/test/scala/io/substrait/spark/LocalFiles.scala

The builds were sporadically failing with the error: 
```
io.substrait.spark.HiveTableSuite > Insert into Hive table FAILED
org.scalatest.exceptions.TestFailedException: Expected 4, but got 5
```
It turns out that the row values were not being correctly serialised / deserialised into the Hive table, so even in the cases were the test passed (based on number of rows added), the values inserted were still incorrect.
This commit fixes that, and adds an extra check in the test cases to assert the correct values are inserted.

fix(spark): sporadic failures in Hive test suite
